import Providers from "@/lib/utils/Providers";
import "./globals.css";
import Header from "@/components/Header";
import ThemeButton from "@/components/ThemeButton";
import TagSearch from "@/components/TagSearch";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <main>
          <Header />
          <TagSearch />
          {/* <ThemeButton /> */}
          <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  );
}
